import Providers from "@/components/Providers";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "@next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tinos = localFont({
  src: [
    {
      path: "../public/Tinos/Tinos-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/Tinos/Tinos-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-tinos",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${tinos.variable} font-sans`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
